### PR TITLE
fix: do not attempt to parse JSONObject scalars

### LINKED ISSUE #427: Metadata object is always empty when retrieving links
Hello,

we created an internal integration to manage links to deployment urls. We want to identify them using the metadata field on "attachments" by adding an id. This field is correctly filled and I can see them when testing with https://studio.apollographql.com/public/Linear-API/variant/current/explorer, but I cant get them using the linear-sdk. 

I tried all the following : 
```
const attachments = await issue.attachments()
const attachment = await linearClient.attachment(id)
```
And everytime I get an empty `medata: {}` property on the result. Is there a way to ask for this property to be in the response ?

thanks

### PR DESCRIPTION
**Pull request by guillaumelachaud**
Resolves #427

### Summary
The `metadata` field on `attachment` is always null, even on entities that do have some metadata. This is caused by an incorrect attempt at parsing `JSONObject` scalars, that fails silently. This actually affects all `JSONObject` fields on all models and has most likely always been broken. The test covering this is actually incorrect and is fixed in this PR.

### Changes
Our schema defines two JSON scalar types, as follows:
```
"""
The `JSON` scalar type represents arbitrary values as *stringified* JSON
"""
scalar JSON

"""
The `JSONObject` scalar type represents arbitrary values as *embedded* JSON
"""
scalar JSONObject
```

The SDK is currently configured to treat both `JSON` and `JSONObject` in the same way through the following [constants](https://github.com/linear/linear/blob/7bf3143750e72feda3e18921b303a94cb9eb3173/packages/codegen-doc/src/constants.ts#L18):
- `SCALAR_JSON_NAMES` is used to generate type `Scalars` in `_generated_documents`, where both `JSON` and `JSONObject` are currently mapped to type `Record<string, unknown>`. 
- `SCALAR_JSON_TYPE`, which value is `Record<string, unknown>` is used to identify JSON scalars in the documents. [printModelScalar](https://github.com/linear/linear/blob/7bf3143750e72feda3e18921b303a94cb9eb3173/packages/codegen-sdk/src/print-scalar.ts#L40C12-L40C12) then relies on this type to determine what needs to be parsed. 

Because of the above, the SDK currently attempts to parse JSONObject fields, which are actually _embedded_ json and do not need parsing. 

The change in this PR simply removes `JSONObject` from list `SCALAR_JSON_NAMES`. These are now mapped to `any` and are not parsed. The SDK will only parse stringified JSON.

It turns out that there is actually a manual (non-generated) test covering this exact usecase. But the test is wrong. The test data was passing `metadata` as a stringified JSON, whereas the schema says it should be a JSONObject. So the incorrect parse attempt would succeed in that case. But in production, API will send embedded JSON for this model and field.

### CODE REVIEW

File: packages/codegen-doc/src/constants.ts [hunk 1]
```diff
@@ -15,6 +15,6 @@ export const Doc = {
   SCALAR_STRING_TYPE: "string",
   SCALAR_DATE_NAMES: ["DateTime", "TimelessDateScalar"],
   SCALAR_DATE_TYPE: "Date",
-  SCALAR_JSON_NAMES: ["JSON", "JSONObject"],
+  SCALAR_JSON_NAMES: ["JSON"],
```
Comment (guillaumelachaud) [inline packages/codegen-doc/src/constants.ts:18]: This is the core change of the PR.

File: packages/sdk/src/_tests/LinearSdk.test.ts [hunk 2]
```diff
@@ -30,9 +30,18 @@ describe("LinearSdk", () => {
...
     const sdk = new LinearSdk(
-      resolveWithData({ attachment: { id: "test", metadata: JSON.stringify({ some: { nested: { data: 123 } } }) } })
+      resolveWithData({ projectUpdate: { id: "test", diff: JSON.stringify({ some: { nested: { data: 123 } } }) } })
+    );
+    const response = await sdk.projectUpdate("test");
+
+    expect((response?.diff?.some as any)?.nested?.data).toEqual(123);
+  });
+
+  it("does not attempt to pars JSONObject", async () => {
```
Comment (tommoor) [inline packages/sdk/src/_tests/LinearSdk.test.ts:42]:
```suggestion
  it("does not attempt to parse JSONObject", async () => {
```

**Review by tommoor — APPROVED** [review]
